### ISSUE TITLE
How to configure Settings Sync without Github Access?

### ISSUE THREAD

**Issue by ranasaria** [shanalikhan/code-settings-sync#1021]
🐛 **Describe the bug**  
Currently to setup settings sync, a user is required to give access to shanalikhan on github for their setting. We should decouple this feature from this dependency so users are not required to give such permissions to another individual

**Comment by shanalikhan** [comment]
As Settings Sync requires two things to setup.

1. GitHub Token
2. GitHub Gist ID

In order to manually configure the Settings Sync. 

1. You need to get the token from GitHub manually with the `gist` permissions. Note the token somewhere. 
2. Create new GitHub Gist and get the ID of Gist.
3. Open the Settings Sync Global Settings (see readme for global settings) and insert GitHub token you saved from 1. and paste the value over there.
4. Paste the GitHub Gist ID in the configuration of `sync.gist` inside Code User Settings.
5. Once these are all done, you can perform upload and download as usual.


Settings Sync required manual creation of token before `v3.4` and users were able to create token to setup Settings Sync, as this feature has been removed and Settings Sync now gets the GitHub token by itself by an application. I would recommend you to use that. Code is open source, you can always clear your assumptions. 

Thanks.
Closing this issue.

**Comment by shanalikhan** [comment]
@CollinChaffin 

> So, as the OP asked, shouldn't this be de-coupled from YOU personally

What do you suggest for it? In any way, the GitHub application needs to be own by someone.

> perhaps instead be an optional convenience grant (for those that do not want to follow the above manual instructions) instead assigned to an audit-able APPLICATION account instead?

So, I think details can be added for users who don't want to provide Grant. I'll add details on the readme.

**Comment by FranklinYu** [comment]
> I think details can be added for users who don't want to provide Grant. I'll add details on the readme.

I would like to see this in ReadMe as well. Or did I miss anything?
