### ISSUE TITLE
Use gist name or description consistent across all extension

### ISSUE THREAD

**Issue by vikas027** [shanalikhan/code-settings-sync#1023]
🐛 **Describe the bug**  
I am trying to use a different name of the gist and have set `"askGistName": true` in `syncLocalSettings.json` but I do not get any prompt asking for the name of the gist. 

🌴 **Visual Studio Code Version :** 1.37.1
🌴 **Code Settings Sync Version :** 3.4.2
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** Official
🌴 **Operating System :** OSX 10.14.5 (18F132) 
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** N.A.
🌴 **Gist Id:** N.A.

📰 **To Reproduce**
1. Cmnd + p, then >
2. Sync: Update/Upload settings

💪 **Expected behavior**
As per the documentation, there should be a prompt asking for the Gist Name.

**Comment by slavdok** [comment]
Same here. As a new user, I spent way too much time thinking maybe I didn't understand how it's supposed to work.

**Comment by shanalikhan** [comment]
What are the steps you are following, I tried.

1. Open Code and Login with Github
2. Clicked on Skip button as i want to create new Gist.
3. Goto Advance Settings and enable `askGistName` to `true` and close the settings.
4. Upload the Process
5. It prompt for the description.

**Comment by slavdok** [comment]
@vikas027 I think I figured it out.

First, when you set `Ask Gist Name` to true, you **also** have to clear `Gist ID`. Then upload settings (and it will prompt for a new name"

Second, `Gist Description` and `Gist Name` are the same thing. If you want to "Save as" a pre-configured new name, remove `Gist ID`, fill `Gist Description` with your desired name and _uncheck_ `Ask Gist Name. **OR** if you want to "Save as" and prompt for a name, then remove `Gist ID`, and set `Ask Gist Name` to true (the `Gist Description` will be ignored in this case).

Third, once a gist is created, you cannot "rename" it through a tool, so changing `Gist Description` or setting/unsetting `Ask Gist Name` does absolutely nothing, **unless** you also clear the `Gist ID` (which creates a new gist as described above).

Fourth. On the GitHub side, it looks like they always list your first file in the gist as the "link", i.e. `yourname / cloudSettings`. Since Settings Sync uploads the first file titled "cloudSettings" you will always see that in the list of gits. Your customized `Gist Description` _or_ the result of your prompt for `Ask Gist Name` is what's shown under it

Lastly, when you want to load one of multiple previously saved gists, either manually change the `Gist ID`, or `F1 > Sync: Reset Extension Settings`, then click `Login with Github`, and you will see a window to pick form existing gist

@shanalikhan This was rather confusing for a new user. Could you at least make `Ask Gist Name` and `Gist Description` consistent? Either use `name` or `description`, not both (not sure what official GitHub terminology is)

Also, I don't know if it's possible to disable the form controls on that custom Sync Settings page, but if so, please don't allow `Ask Gist Name` and `Gist Description` while `Gist ID` is filled in. Only enable these fields when `Gist ID` is clear.

And thank you for the hard work, this extension is a life saver!

**Comment by shanalikhan** [comment]
> This was rather confusing for a new user. Could you at least make Ask Gist Name and Gist Description consistent? Either use name or description, not both (not sure what official GitHub terminology is)

@slavdok alright, sounds good. I will make it consistent.

**Comment by shanalikhan** [comment]
`v3.4.3` Released. Let me know if there is any problem :)
