### ISSUE TITLE
Gist description not being set on Github

### ISSUE THREAD

**Issue by slavdok** [shanalikhan/code-settings-sync#1029]
🐛 **Describe the bug**  
Gist description not being set on Github

🌴 **Visual Studio Code Version :** [ 1.37.1 ]
🌴 **Code Settings Sync Version :** [ 3.4.2 ]
🌴 **Standard or Insiders :** [ standard ] 
🌴 **Portable or Installed :** [ installed ] 
🌴 **OSS or Official Build :** [ Official ] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [Upload ]
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
1. Command Palette > Sync Advanced Options > Sync Edit Extension Local Settings
2. Verify that default `"gistDescription": "Visual Studio Code Settings Sync Gist",` is present
3. Modify some User setting in VSCode
4. SHIFT ALT U to upload settings to GitHub
5. Open the Gist in Github and very description.

💪 **Expected behavior**
Expected behavior is that the Gist's description would be updated. 
It does not get updated

**Comment by shanalikhan** [comment]
Git Description is one time only you cant change the description after creating the Gist.

In order to change the Description you need to create new Gist.

1. Reset the settings.
2. Change the value of `askGistName` to `true`
3. Upload the settings. Upon uploading, it will ask you to write the description of Git.


If it still doesnt work, let me know i will reopen this issue.

**Comment by slavdok** [comment]
I understand the premise.
Unfortunately `askGistName` on `true` doesn't work for me either, as described by another user here
https://github.com/shanalikhan/code-settings-sync/issues/1023

**Comment by shanalikhan** [comment]
Yes, i will look into it.

Thanks!
