### ISSUE TITLE
Store non-confidential settings in the standard way

### ISSUE THREAD

**Issue by flesler** [shanalikhan/code-settings-sync#111]
**Visual Studio Code Version :** 1.5.2
**Code Sync Settings Version :** 2.2.7
**Operating System :** Windows 10

Hi, I wonder why did you decide to store the extension's (non-confidential) settings on syncSettings.json rather than on Default/Workspace/User settings. If I'm not wrong, this extension is (ironically) not syncing its own settings to the GIST.

I think changing them with the commands is cool but overriding them manually on my user settings is definitely not hard.

As a bonus question, I was wondering if there's any cool way to store the token. If you move settings to the standard way, one could for example choose to store it on the general settings, as long as the GIST is private. Otherwise, any suggestion?

Thanks great extension

**Comment by shanalikhan** [comment]
> why did you decide to store the extensions' settings on syncSettings.json rather than on Default/Workspace/User settings.

Initially i didnt think of setting this up in standard way because of token. I already have this on mind. will work on that once i add all required features and after that i will change the settings to standard VSCode way if i find the alternative way for token.


>I was wondering if there's any cool way to store the token. If you move settings to the standard way, one could for example choose to store it on the general settings, as long as the GIST is private. 

Do you have any suggestion for this when the GIST is public anyone can see, i cant even save token in encrypted form due to open source code.

**Comment by flesler** [comment]
Not sure about how to solve it when it's public. It's very hard to store credentials securely out in the open. I suggested it could be optional to use the standard VS settings for the case when it's private. If you go this way, you should make sure the token is removed if the user switches to public GIST, or show a warning

**Comment by shanalikhan** [comment]
So you mean i have to use both of the settings, 
when GIST is private - VS Standard Settings
and when GIST is public - Current Settings File.

> You keep it in the "private" JSON

It will be become more complicated, user need to remember GIST type in order to check the settings as for now , user may open the simple setting file to edit anything without having consent of GIST type.

May be there can be other options but at the end the settings should be saved in one place rather than multiple place and become dependent on GIST type. 
Is there any possible way to add token and GIST in Code own memory storage somehow that wont be synced though but just to write there and other settings can be saved in default standard code settings.

**Comment by flesler** [comment]
I meant you move regular settings to VS Settings and keep auth where it is now.

Then add a way to get the token and GIST easily via VS Command Line if one needs to use them on another computer.

**Comment by shanalikhan** [comment]
I have completed the code migration to make complete ready for version 2.4.
It would be great if you can check it, too to - by pulling the code and running the code.
Make sure you have a backup for extension syncsettings.json as it will remove that file and save all those settings in the code default settings file.

**Comment by shanalikhan** [comment]
Published to Insiders. - Version 1.9+
Version 2.4.
If all works well i will publish it to normal build

**Comment by shanalikhan** [comment]
Released for all users Version 2.4.2
https://github.com/shanalikhan/code-settings-sync/releases/tag/v2.4.2
