### ISSUE TITLE
Latest version of vscode comes with settings sync

### ISSUE THREAD

**Issue by sbungert-mms** [shanalikhan/code-settings-sync#1211]
https://code.visualstudio.com/updates/v1_45

Is it your extension integrated into vscode? If not, are you carrying on with the development of the extension?

**Comment by Progdrasil** [comment]
It's still only available on the vs-code insiders build. I am still curious about the future of this project once it does hit the stable build

**Comment by Smi1e96** [comment]
![image](https://user-images.githubusercontent.com/31199247/84334094-0ab81f80-abc4-11ea-9c42-549ab2d509d2.png)

😄

**Comment by entozoon** [comment]
Yes @Progdrasil, we need to know when it will be incorporated in the the stable build is it a direct replacement for this extension, and will it magically migrate the settings.

**Comment by shanalikhan** [comment]
> Is it your extension integrated into vscode? If not, are you carrying on with the development of the extension?


VS Code has its own Settings Sync, with Microsoft backend.
This Settings Sync use GitHub backend.

I'm currently not maintaining this extension due to other work. But **i'm urgently looking for collaborators** to work with me to maintain this extension and improve this further more where VSCode Settings Sync doesnt want to work.

https://github.com/shanalikhan/code-settings-sync/issues/1188
