### ISSUE TITLE
Game Over

### ISSUE THREAD

**Issue by theAkito** [shanalikhan/code-settings-sync#1244]
https://code.visualstudio.com/docs/editor/settings-sync

The official built-in Settings Sync was just released for the stable version of Visual Studio Code.

What now?

Does this extension offer anything that will make people use this one instead of the built-in official Settings Sync?

**Comment by DavidGerva** [comment]
Yes @theAkito. And you can read something here: https://github.com/shanalikhan/code-settings-sync/issues/1188#issuecomment-633305500

**Comment by theAkito** [comment]
Okay, fine but this is only a single feature that will be at least worked around in the official Settings Sync probably, as well.

Additionally, there has been a response to this:
https://github.com/microsoft/vscode/issues/92393#issuecomment-601333291

**Comment by macintacos** [comment]
In the spirit of [dotfiles](https://dotfiles.github.io/), the ability to store my settings in a public gist so that I can share it with others is something that isn't supplied by Microsoft's implementation from what I can tell, and I share that all the time with folks who want to see what my setup is like. [Here's my gist](https://gist.github.com/macintacos/d6476dba5ec0a560c674cef5fdba969f).

I would hope that this extension doesn't go away until Microsoft adds that functionality.

**Comment by macintacos** [comment]
In the spirit of my previous comment, I opened the following feature request: https://github.com/microsoft/vscode/issues/105163
