### ISSUE TITLE
can not upload settings after upgrade to 2.3.6

### ISSUE THREAD

**Issue by enkows** [shanalikhan/code-settings-sync#130]
**Visual Studio Code Version :** 1.7.1
**Code Sync Settings Version :** 2.3.6
**Operating System :** macOS 10.12.1
**Occurs On:** Upload
**Proxy Enabled:** No

Please make sure to write the versions and console logged error picture or copied text.

```
// extensionHost.ts:255
{"message":"Validation Failed","errors":[{"resource":"Gist","code":"missing_field","field":"files"}],"documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}
```

**Comment by shanalikhan** [comment]
This may be due to some latest changes in your settings file since the last upload that is causing posting fails in Github.
try creating new GIST by removing the GIST in the settings.

If the error is still there, please tell which settings file you have changed since the last upload and which content.

**Comment by enkows** [comment]
Thanks! 
I didn't changed anything but it works on 2.3.7 now.
