### ISSUE TITLE
Network issue : Internet Not connected

### ISSUE THREAD

**Issue by clemtoy** [shanalikhan/code-settings-sync#235]
**Visual Studio Code Version :** 1.9.1
**Code Settings Sync Version :** 2.4.4
**Operating System :** Windows 7
**Occurs On:** Upload / Download
**Proxy Enabled:** Yes
**GIst Id:** 1724e7e7fd3ffa943db37d6c8a5fd4d3bc3caa02

My proxy settings are OK (I can download new vscode extensions) but when I want to upload or download my settings I get this message : 
![image](https://cloud.githubusercontent.com/assets/5541136/23253974/aa2d66c4-f9b6-11e6-9998-95de928818f1.png)

Log message:
![image](https://cloud.githubusercontent.com/assets/5541136/23253837/323d47d8-f9b6-11e6-879a-61cb16fb9b9b.png)

I don't understand what happens.

**Comment by shanalikhan** [comment]
I wont be able to reproduce this error due to proxy environment settings.
Previously users sent me pull request to solve the proxy issues.

If you have time, you can download the code by placing the commands written here and send me pull request, i will accept that and hopefully extension will be more compatible with proxy environments.
https://github.com/shanalikhan/code-settings-sync#through-code

**Comment by shanalikhan** [comment]
as this was coming from github API.
can you try for this extension for code insiders i have updated the Github API and v2.6.0 that is available for insiders at the moment.
