### ISSUE TITLE
"You already have latest version of saved settings". Only I don't

### ISSUE THREAD

**Issue by barbalex** [shanalikhan/code-settings-sync#466]
**Visual Studio Code Version :** 1.18.1
**Code Settings Sync Version :** 2.8.6
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** https://gist.github.com/barbalex/79369e499807ccf816d8ad586a20df5d

This happened after I realized I only had one single extesion installed: Settings Sync.

Then I ran "Sync: Download Settings". And get "You already have latest version of saved settings".

The sync.gist setting is correct.

The gist contains a whole lot of extensions.

What am I doing wrong?

Yesterday I had an epic battle trying to download the settings on to a new notebook (https://github.com/shanalikhan/code-settings-sync/issues/461#issuecomment-350009236 and following comments). Maybe something happened there.

**Comment by barbalex** [comment]
I found a setting called: `sync.forceDownload`, set it to true, ran `Sync: Download Settings`.
And now I have 20 installed extensions again.

Hm.

**Comment by shanalikhan** [comment]
I see your comments here. (https://github.com/shanalikhan/code-settings-sync/issues/461#issuecomment-350314339)

You may suggest ways in order to make extension more easy to use. - even contribute in readme
I will ask token every time when its not entered when user download on second machine before gist ( which i disabled as for download its not required)
