### ISSUE TITLE
Can't download settings from public gist

### ISSUE THREAD

**Issue by tedhudek** [shanalikhan/code-settings-sync#487]
**Visual Studio Code Version :** 1.19.2
**Code Settings Sync Version :** 2.8.7
**Operating System :** Windows 10 RS3
**Occurs On:** Downloda
**Proxy Enabled:** No
**GIst Id:** [ ID_HERE ]

@shanalikhan, to expand on my comment in #471, this common scenario does not work for me.

1. On machine A, upload settings to a public gist.
2. On machine B, reset settings.
3. On machine B, download settings.  It prompts for token, but none is needed because the gist is public.  If I press Esc, it cancels out and does not download.

I even tried manually adding the public gist id in user settings json on machine B, but same result.  How can I download settings successfully on machine B?  Thanks

**Comment by shanalikhan** [comment]
can you verify setting `sync.anonymousGist` to `true` and then download the setting.

**Comment by vesper8** [comment]
I can verify that setting anonymousGist to true allows you to download without token

however this is confusing, even more now that Github is deprecating anonymous gists

I think the wording should be modified since anonymous gists are no longer possible
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by shanalikhan** [comment]
Thanks for providing information, i think i should remove the `anonymousGist` feature.
and change it with public gist

**Comment by shanalikhan** [comment]
Released with v2.9
Let me know if there are issues

**Comment by vesper8** [comment]
well.. i'm sorry to say @shanalikhan but we're having problems with this update

previously I had been able to download the settings WITHOUT generating a token, and without making the gist public

it was working just fine with a secret gist.. it was not anonymous.. but it was secret.. and it was possible for others to download from it without needing to make it public, and also more importantly without them needing to generate a token

now it seems a token is mandatory?

i know you need a token to make a gist, but why do you need one to download?

anyway my freelancer friend is unable to download now after I made the gist public and gave her the gist id.. it is forcing her to generate a token but a few days ago that wasn't the case

**Comment by vesper8** [comment]
yea I just used Teamviewer to log in to my freelancer's computer and can confirm things are not working as they should

I created a public gist with my settings and gave her the gist id. Then from her computer I tried to goto Advanced Options -> Download from public gist and it prompted me for the gist id. I put it in and then it complained about invalid or expired token

then I actually had her create a token with her own github account, but the error is still there

I also tried to reset the extension settings but it didn't help

like I said above, a few days ago I was able to download from a secret gist (not to be confused with an anonymous gist) without creating a token or even logged into github.. but now this doesn't seem to work at all anymore

**Comment by wongjiahau** [comment]
Oh my goodness, this is so frustrating! I just wanted to download the settings I have from another laptop, is there a way that I can do without generating a Github Token?

**Comment by willingram** [comment]
Had the same issue, as a workaround you can paste the public GIST id directly into the `Sync: Gist` setting in the VS Code settings menu and perform the `Sync: Download Settings` actions as normal.

**Comment by robertmarriott** [comment]
I agree. This is really frustrating. The configuration of this extension is not user-friendly. All I want to do is pull the settings from a public gist I created. Like wongjiahau, I don't want to create a new github token because the gist is already publicly visible. I tried pasting the URL of the github gist into the extension settings, as suggested by willingram, but I still get an error popping up when I attempt a to download. The error says to look at the developer tools console and when I do, it says "TypeError: Cannot read property 'gists' of null
	at module.exports.t.GitHubService.<anonymous>"

**Comment by sebastien-p** [comment]
Same as @robertmarriott here, what can we do @shanalikhan? Thanks :)

**Comment by tpatel11** [comment]
I was having the same issue but I got it working. After trying few things, I went back and I tried uploading the settings from my source machine and it gave me the information like below in output window in VSCode:
`GitHub Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GitHub Gist: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GitHub Gist Type: Secret`

Now on my other machine, when asked for Token enter the token (GitHub Token above) and when it asks for Gist ID enter the Gist ID (GitHub Gist above).  It works after that.

**Comment by robertmarriott** [comment]
tpatel11 correctly pointed out that the gist has to be entered with the ID [only], and not the complete URL. There error went away after I did that [and] entered my token.

However, this extension uploaded the settings from my fresh install of VS Code and now my gist on github is competely overwritten -- wiped out! That wouldn't have happened if the extension allowed you to download the settings in read-only mode (i.e. by not forcing you to enter a token).

IMHO, the configuration of this plugin is overly complicated. That said, this functionality really should have been built into VS Code in the first place. We shouldn't need a third-party extension in order to share environment settings between workstations.

**Comment by gund** [comment]
Same error here. Installed fresh vscode + settings sync and got:
```
TypeError: Cannot read property 'gists' of null
	at module.exports.t.GitHubService.<anonymous> (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:419:31978)
	at Generator.next (<anonymous>)
	at module.exports.n (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:419:30419)
	at new Promise (<anonymous>)
	at module.exports.n (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:419:30196)
	at module.exports.t.GitHubService.ReadGist (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:419:31920)
	at /home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:81729
	at Generator.next (<anonymous>)
	at module.exports.n (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:76170)
	at new Promise (<anonymous>)
	at module.exports.n (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:75947)
	at /home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:81490
	at module.exports.t.Sync.<anonymous> (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:85259)
	at Generator.next (<anonymous>)
	at s (/home/gund/.vscode/extensions/shan.code-settings-sync-3.2.8/out/extension.js:130:76003)
```

Providing token does not work and neither public/anonymous gist!

**Comment by nazares** [comment]
Version: 3.4.3 with  macOS
uploads work properly but downloads work only with extensions and I can't download settings.json

**Comment by shelper** [comment]
same problem here too
