### ISSUE TITLE
Error on attempt to sync settings

### ISSUE THREAD

**Issue by con-ssc** [shanalikhan/code-settings-sync#64]
**Visual Studio Code Version :** [ VERSION_HERE ]
![image](https://cloud.githubusercontent.com/assets/8189808/17729504/cfabd738-6464-11e6-81aa-bad5285d3966.png)

**Code Sync Settings Version :** [ VERSION_HERE ]
![image](https://cloud.githubusercontent.com/assets/8189808/17729518/e1e82208-6464-11e6-840b-eae8ece5b968.png)

**Operating System :** Win 10 x64

Please make sure to write the versions and console logged error picture or copied text.
![image](https://cloud.githubusercontent.com/assets/8189808/17729490/c1ac3d9e-6464-11e6-9f8f-96618967a116.png)

I'm still unable to upload settings from Visual Studio Code Insider

**Comment by shanalikhan** [comment]
This issue is duplicate to older issue, i suppose 
[#48](https://github.com/shanalikhan/code-settings-sync/issues/48).

Its in my backlog, i am currently working on Automatic syncing feature, [#31](https://github.com/shanalikhan/code-settings-sync/issues/31). Soon im done with that feature, i will start working on it.
