### ISSUE TITLE
@sync-ignore isn't ignoring my local value, it deletes it

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#686]
The latest 3.2.0 release implemented `@sync-ignore` pragma, see #640, but I don't think it's working as expected.

These were my steps to reproduce:

1. Add `// @sync-ignore` before `"window.zoomLevel": 1`.
2. Upload
3. Download (forced download to be sure)

I would expect that my local `settings.json` still contains this:

```
    // @sync-ignore
    "window.zoomLevel": 1
```

but it didn't, these two lines were removed. _Removing_ is not _ignoring_. In practice, this messes up my `zoomLevel` every time I invoke download which is unpleasant.

**Comment by shanalikhan** [comment]
@ioprotium can you look into it

**Comment by ioprotium** [comment]
@shanalikhan sure. The problem comes from the Sync settings initial behavior. When settings are downloaded it overwrites the entire file. We should compare the existent file and extract all the `@sync-ignore`  in order to merge them with the downloaded settings before writing the file. 

That shouldn't be difficult. But we need to define the following: when we merge the settings in order to keep the ignored ones, those will be
- At the beginning of the file 
- At the end
- Every ignored setting should keep its own line position // this will be a little tricky I think

What do you think? 
To fix this should I pull from master or some other branch?

**Comment by shanalikhan** [comment]
> In my opinion, keep all the sync-ignored at the beginning of the file could be a good practice to make more readable the settings file.

yes, thats perfect.

For PR, you can pull from `master`.

**Comment by ioprotium** [comment]
@shanalikhan Today I will start with this. Sorry for the delay, busy week at work.
