### ISSUE TITLE
command 'extension.downloadSettings' not found

### ISSUE THREAD

**Issue by Green-unicorn** [shanalikhan/code-settings-sync#745]
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version ： 1.30.1
🌴 **Code Settings Sync Version :  3.2.4
🌴 **Operating System : win10

I'm  installed version 3.2 of this plugin successfully and restart vscode, but I can'n upload or downloadSettings. The error messages is  `command 'extension.downloadSettings' not found`.
I uninstalled and installed vscode again, but this error still exists

**Comment by jotatoledo** [comment]
Same issue, above instructions had no effect.

palm_tree **Visual Studio Code Version ： 1.30.1 (system setup)
palm_tree **Code Settings Sync Version : 3.2.4
palm_tree **Operating System : Windows_NT x64 6.1.7601

**Comment by jdshkolnik** [comment]
Setting up a new machine and encountered this same problem.

**Comment by po9357** [comment]
same problem here

**Comment by Jasius** [comment]
> Remove the Settings Sync, check if the extension folder is removed, if not removed - Delete the folder.
> Install Settings Sync again.

This worked for me, thanks.

**Comment by shanalikhan** [comment]
I have updated the packages with the latest versions in the latest version v3.2.5
Make sure you are using latest version of vscode.


Remove the Settings Sync, check if the extension folder is removed, if not removed - Delete the folder.
Install Settings Sync again.

Let me know if it fix

If error is still there, post the image of error from the vscode console.

**Comment by fullenw1** [comment]
Uninstalled the extension and removed the folder.
`ri $home\.vscode\extensions\shan* -re -fo `
Still same problem...
![sync_extension](https://user-images.githubusercontent.com/23318240/52859787-efebad00-312d-11e9-8fad-84ffb4498342.png)

**Comment by shanalikhan** [comment]
is there any  exception logged in console ? for vscode

**Comment by fullenw1** [comment]
No exception. The Output view of the terminal is empty.
I can only view this in the Log (Extension Host):
`[2019-02-21 19:01:30.167] [exthost] [info] ExtensionService#_doActivateExtension Shan.code-settings-sync {"startup":true,"activationEvent":"*"}`
`[2019-02-21 19:01:30.167] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\UserName\.vscode\extensions\shan.code-settings-sync-3.2.5\out\extension.js`
`[2019-02-21 19:01:30.370] [exthost] [info] eager extensions activated`

**Comment by shanalikhan** [comment]
> The Output view of the terminal is empty.

Console error are logged on Developer tools 
Help menu > Toogle Developer Tools.

Paste a screenshot after producing that error so i can further investigate.

**Comment by fullenw1** [comment]
Here you are:
![VSSynError](https://user-images.githubusercontent.com/23318240/54910280-4a75e700-4eec-11e9-862f-fcffcb90df1b.png)

**Comment by ShinobiWPS** [comment]
Getting same error, tried with folder trick, nothing changed.

**Comment by shanalikhan** [comment]
Another method you guys can try:
1. Download the extension last update [link](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Shan/vsextensions/code-settings-sync/3.2.8/vspackage) - Or open the [page](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) and Click `Download Extension` to download the extension package. 
2. Install extension via command line

`code --install-extension Shan.code-settings-sync-3.2.8.vsix`

Restart the Code to see if it helps.

Because its might be occurring to due network issue while downloading from code itself.

**Comment by fullenw1** [comment]
What I've done:
1. Uninstall the extension in VSCode
2. Downloaded the VSIX file
3. Click on the three dots at the top of the Extensions side bar and chose "Install from VSIX"
4. Reload VSCode

Got the same error :-(

Recently I had an issue with the PowerShell extension. And this happened because on a particular computer I was not using a workspace.
For your extension, I tried both with and without workspace but still get the same error.

This is a pity because your extension is so useful on my other computers. :-(

**Comment by shanalikhan** [comment]
Try with the latest version of Settings Sync v3.3.0.

**Comment by chris-pearce** [comment]
I am also getting this, I tried all the suggestions and none of them worked.

**Comment by fullenw1** [comment]
I installed version 3.4.1 and have still the same issue.

**Comment by jiaqiu-09** [comment]
It's now 2019/11/20 10:55 PM.
Unfortunately, I got the same issue.
Visual Studio Code Version ： 1.40.1
Code Settings Sync Version : 3.4.3
Operating System : MacOS 10.15.1
:-( :-( :-( :-( :-( :-(
<img width="1131" alt="截屏2019-11-20下午10 59 50" src="https://user-images.githubusercontent.com/15116421/69249976-c7776e80-0be9-11ea-8ed1-3a433d371230.png">

**Comment by ddzy** [comment]
`2019/11/28`
The same issue!

**Comment by devcfgc** [comment]
Same issue :'( on Ubuntu 18.10.... pretty weird but this worked for me:
https://github.com/shanalikhan/code-settings-sync/issues/78#issuecomment-318495738
