### ISSUE TITLE
How do I replace github's token login

### ISSUE THREAD

**Issue by developers-youcong** [shanalikhan/code-settings-sync#772]
Settings-sync plug-in USES github token for login and gisit for storage.
However, I want to log in the token of my blog system account developed by myself, and use cloud storage to synchronize relevant code segments and Settings. In short, I'm replacing github's token login with my own blogging system.

**Comment by shanalikhan** [comment]
You need to clone the repo.
Write your own service like github service
https://github.com/shanalikhan/code-settings-sync/blob/master/src/service/githubService.ts

In order to implements yours.

**Comment by developers-youcong** [comment]
Thank you!

By the way, your plug-in is packaged with webpack, but I use webpack to package, why is the error report display not available?

My process is as follows:

"Scripts" : {

"Vscode :prepublish":" NPM run tslint-check && webpack --mode production",

"Compile" : "webpack",

"Watch ": "webpack --mode development --watch",

"Postinstall" : "node. / node_modules/vscode/bin/install",

"Tslint - check", "tslint - c. / tslint. Json. / SRC / / *. * * ts. / SRC / * ts".

"Format" : "prettier - write '. / SRC / / * * *. Ts'".

"Test", "NPM run tslint - check && TSC - p. / && mocha -- recursive \".. / out/test / * * / *. Js \ ""

}

Mainly refer to webpack.config.js

But they always report an error.

If possible, please send your packaging process command for my reference.

**Comment by developers-youcong** [comment]
Common.ts, where this code is shown below:


If (askToken) {

If (cusSettings. OpenTokenLink) {

// replace the github token here with my own

Vscode.com mands. ExecuteCommand (

"Vscode. Open",

Vscode. Uri. Parse (" https://github.com/settings/tokens ")

);

}


If I rewrite githubService, I major changes should be the https://github.com/settings/tokens


After changing it to a token generated by my own business url. This means that I don't intend to use gist, but my own cloud storage. Is it mainly to modify githubService? Still?

**Comment by shanalikhan** [comment]
> If possible, please send your packaging process command for my reference.

you need to run `vsce package` in order to create the extension package. If you are getting error try running compile command and other commands to see the errors.

> Is it mainly to modify githubService?

Yes see the create gist and save gist functions in the githubservice that uploads and create gist.

As you are working on order to create yours token generation and upload and download. 
I will suggest you to work in a way that Settings Sync will also get improved from your way as I'm also looking to decouple the github and integrate more options like generating simple json file and store in local drive instead of uploading.

You need to create interface and implement that interface in two classes `githubService` and your cloud storage.
In this way you can send me a PR of improved githubservice with interface implements and you can use your own cloud implementation with custom build, it will help the other users to write the implementation to use `git` instead of `gist` and `filesystem`.

I hope you understand, let me know i am available to help.

**Comment by developers-youcong** [comment]
For your first question:

My packaging process is as follows:

npm run vscode: prepublish

npm run the compile

npm run watch

npm run postinstall

npm run tslint - check

npm run format


The main reference is the script in your package.json.


For your second question:


Thank you very much for your detailed answer.


By the way, by the way, I have read your githubService code, which is mainly related to github rest API.



After your answer and my thinking, I have so many ideas at present?

First, the idea that you put forward;

Second, I think you now that is a lot rest API, I try to build a mock server, by making a rest API, equivalent to a request to the server address to replace for my server address (my server address, in this equivalent to making server), and making a rest API request to this address, in order to achieve the use of my blog to achieve replacement, mainly I want to reuse your code to the greatest extent, reduce the writing your own.


Of course, in addition to the tests I have done, I would like to propose a simple requirement to you:

Github token login and gist storage mainly adopted in Setings-Sync, for example, will result in token failure when I replace it with gitlab. I think it is because there is not a gist store in the token generated by gitlab.

Gitlab mainly USES ruby on rails as its web framework, while gist is adopted for storage.

Requirements: if github is unstable or is aborted, should appropriate forms of Setings-Sync not be available?

Therefore, I think you'd better use setting-sync in more ways, such as using other accounts, such as facebook, twitter, etc., or customizing your system account. If it is your account, you can use No Sql database for storage. I think it's better this way. Currently, github, such as wiki or other related resources, is free, and there is no guarantee that it will be.


All in all, I think you should add your own account from settings-sync to make it easier to collect and analyze data.


These are some of my personal thoughts.

**Comment by developers-youcong** [comment]
![image](https://user-images.githubusercontent.com/45055576/52993209-5fbfa780-344e-11e9-9d07-65ee567000c3.png)
I put the source code directly into the extension folder in vscode, which is generally for plug-ins.

But after I put it in, why did the display need to be reloaded when I searched the plug-in market?

When I click reload, it is equivalent to downloading under the current extension folder. Do you have to package the plug-in so it doesn't reload? Still?

**Comment by shanalikhan** [comment]
Actually instead of supporting GitLab, and other tools. 
there is already issue opened that intends to support the Settings Sync with simple git repository, its the user choice on pushing the complete repository on github, gitlab or any other git services - That issue is paid one, If you are willing to work, feel free to start working on that one. Payment will be made once it completes.

See : https://github.com/shanalikhan/code-settings-sync/issues/413


> But after I put it in, why did the display need to be reloaded when I searched the plug-in market?

I dont understand, can you explain further.
