### ISSUE TITLE
Remove replaceCodeSettings from Settings Sync configurations

### ISSUE THREAD

**Issue by shanalikhan** [shanalikhan/code-settings-sync#805]
Replace `replaceCodeSettings` from the Settings Sync.

1. User should use Sync Pragma in order to disable upload of certain settings.
2. Use `host` in order to switch the settings to other host.

Reference : https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas

**Comment by darkvertex** [comment]
Hi there,

Forgive me if this question seems obvious, but the wiki page on "Sync Pragmas" is not 100% clear to me.

Do I use them directly in my settings.json that vscode uses for my user preferences? And if so, say I have 2 settings where I need values different per OS... Do I do this:
```
    // @sync os=linux
    "git.defaultCloneDirectory": "~/repos",
    // @sync os=windows
    "git.defaultCloneDirectory": "",
```
(which VSCode warns me is wrong because of "duplicate keys", so I'm guessing it's wrong..)
...or...
```
    // @sync os=linux
    "git.defaultCloneDirectory": "~/repos",
    // @sync os=windows
    // "git.defaultCloneDirectory": "",
```
and I can expect the good one to get uncommented should I sync on my Windows laptop? Is that how it's supposed to work?

Furthermore, what about multi-line settings... Do I need to apply the pragma comment per individual line? Or do I declare it twice like the previous example and declare it just before declaring a multiline pref?

Basically, do I do this below?
```
    "python.autoComplete.extraPaths": [
        // @sync os=linux
        "/mnt/users/alan/.local/lib/python2.7/site-packages",
        // @sync os=linux
        "/usr/lib/python2.7/site-packages",
        // @sync os=windows
        "C:\\Program Files\\Anaconda3\\lib\\site-packages",
    ],
```
or this below?
```
    // @sync os=linux
    "python.autoComplete.extraPaths": [
        "/mnt/users/alan/.local/lib/python2.7/site-packages",
        "/usr/lib/python2.7/site-packages",
    ],
    // @sync os=windows
    "python.autoComplete.extraPaths": [
        "C:\\Program Files\\Anaconda3\\lib\\site-packages",
    ],
```
or one commented like this below? (let's say I'm in Linux at the time)
```
    // @sync os=linux
    "python.autoComplete.extraPaths": [
        "/mnt/users/alan/.local/lib/python2.7/site-packages",
        "/usr/lib/python2.7/site-packages",
    ],
    // @sync os=windows
    // "python.autoComplete.extraPaths": [
    //     "C:\\Program Files\\Anaconda3\\lib\\site-packages",
    // ],
```

I would like to know which is the good syntax (and if you can later clarify it in the wiki page so it's clearer for others that would be great too.)

Thank you for an awesome extension btw!

**Comment by ctf0** [comment]
@darkvertex according to 
> Before uploading your settings.json all the settings with inline pragmas are uncommented. Then, when your settings are synchronized, all the settings values with pragmas that don't match with your machine (OS, hostName or ENV variables) will be commented. Therefore VS Code won't apply them.

so i think a combination of ur first & second examples is what happens, @shanalikhan any insights ?

**Comment by Soxcks** [comment]
I echo these confusions in my comment here: https://github.com/shanalikhan/code-settings-sync/issues/753#issuecomment-495460505
