### ISSUE TITLE
Allow forced re-downloading of current settings from the cloud

### ISSUE THREAD

**Issue by mklement0** [shanalikhan/code-settings-sync#91]
Visual Studio Code Version : [ 1.4.0 ]
Code Sync Settings Version : [ 2.2.3 ]
Operating System : [ OSX 10.11.6 ]

Currently, you cannot re-download current settings after making local modifications you wish to revert: message `You already have the latest settings version of saved settings.` is displayed.

However, it would be handy to allow making experimental local modifications and then revert to the latest cloud-saved settings by re-downloading them.

**Comment by shanalikhan** [comment]
Check this link with the settings, how you can change to allow force download.
[edit settings](http://shanalikhan.github.io/2016/07/31/Visual-Studio-code-sync-setting-edit-manually.html)

**Comment by mklement0** [comment]
Thanks, this definitely helps in a pinch (it works, but it's arcane and inconvenient).

However, I suggest turning this into a _feature_ (not sure if it's feasible):

If a users requests re-downloading the most recently downloaded files, show a _prompt_ that warns of potentially reverting locally modified files (which may be the user's very intent), thus giving the user a chance to either proceed with reverting, or to back out.

**Comment by shanalikhan** [comment]
Showing confirmation box every time when changed when people opens code will not be feasible instead i have to give them option in that case too to have clean and quite install instead of reverting modified files.

This can be turned into feature but it will be least priority to make it a feature in the end, once other bugs or request are completed or extension is mature. May be you have re post this idea after several months then we will see what can be done. :)
