### ISSUE TITLE
Remove translations (at least German)

### ISSUE THREAD

**Issue by levrik** [shanalikhan/code-settings-sync#997]
The German translation is just complete non-sense. Please remove it again or sign up on a translation platform so the community can contribute high quality translations.
I tried to translate it properly but with the JSON files that's not really a good process.
At least add an option to overwrite the language configuration of the extension. I have VS Code set to German but would like to have this extension set to English.

**Comment by shanalikhan** [comment]
> The German translation is just complete non-sense, I tried to translate it properly
PR is welcome for it if you think you can improve.

> I have VS Code set to German but would like to have this extension set to English.

Extensions need to be consistent with the localization of VSCode. So this is out of scope. Either you need to use VSCode in english to see Settings Sync in english or improve the German Support. I'm already alot of PR for other languages, you can also improve the german language JSON files- I will be more happy to accept that.

**Comment by mi-hol** [comment]
@shanalikhan please reopen this case because 'Extensions need to be consistent with the localization of VSCode' is  actually not implemented.
My scenario:
Windows OS is German, my regional setting is English-US user interface language, VS code menue are therefore all in English but 'Edit Settings' displays text in German!
![image](https://user-images.githubusercontent.com/22799428/62854196-de571c80-bcee-11e9-8b0a-89c80343d685.png)
![image](https://user-images.githubusercontent.com/22799428/62854277-26763f00-bcef-11e9-9f5b-fbd9bdb3c1b9.png)

Its a common pitfall for application developers to confuse User and OS settings for locales.
A good reading is https://devblogs.microsoft.com/setup/the-differences-between-locales-and-languages/
